site_name: "I'm Yash Kale" 
site_url: https://imyashkale.com
site_description: >-
  Explore 'I'm Yash: Exploring Code & Cloud,'
  a portfolio showcasing my journey in Golang, AWS, and Kubernetes.
  Here, I share my projects, insights, and experiences in software development.
  Dive into my world of coding and cloud solutions, where technology meets creativity.


nav:
  - Home: index.md
  - Kubernetes:
    - Index: kubernetes/index.md
    - CKAD Kubectl Cheat Sheet: kubernetes/ckad-cheat-sheet.md
    - CKAD YAML Samples: kubernetes/ckad-sample-yamls.md
  - CI/CD:
    - Index: cicd/index.md
    - Github Actions: cicd/github-actions/mkdocs-deployment.md
  - Others:
    - MKDocs: others/mkdocs.md
    - AcloudGuru: others/acloudguru.md
    
theme:
  name: material
  favicon: terminal.png
  icon:
    logo: fontawesome/solid/terminal
  font:
    text: Fira Code
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; Yash Kale

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/imyashkale
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/imyashkale/

  analytics:
    provider: google
    property: !ENV GOOGLE_TAG_MANAGER
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1 
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

