site_name: "I'm Yash Kale" 
site_url: https://imyashkale.com
site_description: >-
  Exploring Code & Cloud,'
  a portfolio showcasing my journey in Golang, AWS, and Kubernetes.

copyright: Copyright &copy; Yash Kale
############################################## NAVIGATION ############################################

nav:
  - Home: 
    - Home: index.md
    - Timeline: timeline.md
  - Projects: 
    - Index: projects/index.md
    - URLify Hub - Microservices-Driven URL Shortener: projects/urlify-hub.md
    - Microforge - Creation & Management of Microservices: projects/microforge.md
    - Infra - Infrastructure for Bare Metal Kubernetes Cluster Using Terraform on AWS EC2: projects/infra.md
    - Scriptor - Streamlining Script Management: projects/scriptor.md
    - Field Validator: projects/field-validator.md
    - Mongo GO API: projects/mgo-crud.md
    - AliceBlue SDK: projects/go-aliceblue-sdk.md
  - Blog:
    - Index: blog/index.md
    - Pinned Post: blog/pinned.md
  - Notes: 
    - Index: fundamentals/index.md
    - OS: fundamentals/os.md
  - Blueprints:
    - Index: blueprints/index.md
    - Product Development: blueprints/services/product-development.md
    - Serverless Architecture: blueprints/services/serverless-architecture.md
    - Cloud Consulting: blueprints/services/cloud-consulting.md
    - Infrastructure Automation: blueprints/services/infrastructure-automation.md
  - Tags: tags.md

############################################## THEME ############################################

theme:
  name: material
  custom_dir: overrides
  favicon: assets/img/favicon.ico
  icon:
    logo: fontawesome/solid/terminal
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

############################################## FEATURES ############################################
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.instant.progress
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

############################################## EXTRA ############################################

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/imyashkale/
    - icon: material/github
      link: https://github.com/imyashkale
    - icon: material/certificate
      link: https://www.credly.com/users/imyashkale/badges
    - icon: fontawesome/solid/code
      link: https://leetcode.com/imyashkale/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/imyashkale
    - icon: fontawesome/solid/earth-asia
      link: https://imyashkale.com

  analytics:
    provider: google
    property: !ENV GOOGLE_TAG_MANAGER
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1 
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
            
############################################## PLUGINS ############################################

plugins:
  - search
  - glightbox
  - social
  - tags:
      tags_file: tags.md
  - blog:
      blog_toc: true
      categories: true      
      
############################################## MARKDOWN EXTENSIONS ############################################

markdown_extensions:
  # For Formatting. https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  # For Images
  - md_in_html
  # For Tabs
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
############################################## Extra CSS ############################################

extra_css:
  - stylesheets/extra.css