name: Deploy MkDocs to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: '3.x'   
  AWS_REGION: 'us-east-1'
  S3_BUCKET_NAME: 'imyashkale-portfolio'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        pip install mkdocs mkdocs-material pymdown-extensions

    - name: Build MkDocs Site
      run: |
        mkdocs build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync Directory to S3
      run: |
        aws s3 sync site/ s3://${{ env.S3_BUCKET_NAME }}/ --delete

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
