name: Deploy MkDocs to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # specify the Python version

    - name: Install Dependencies
      run: |
        pip install mkdocs

    - name: Build MkDocs Site
      run: |
        mkdocs build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync Directory to S3
      run: |
        aws s3 sync site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --delete

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
